<a href="https://colab.research.google.com/github/haeshal25/myreposit/blob/main/ImageCaptioning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!unzip Flicker8k_Dataset.zip

Streaming output truncated to the last 5000 lines.
 extracting: 1650280501_29810b46e5.jpg
 extracting: 2052953131_30834196fb.jpg
 extracting: 2083778090_3aecaa11cc.jpg
 extracting: 2089555297_95cf001fa7.jpg
 extracting: 2195887578_3ba2f29b48.jpg
 extracting: 2230067846_74046b89d3.jpg
 extracting: 2264316030_600e55748d.jpg
 extracting: 2271671533_7538ccd556.jpg
 extracting: 2420730259_86e7f8a815.jpg
 extracting: 2602085456_d1beebcb29.jpg
 extracting: 2687672606_275169c35d.jpg
 extracting: 2750867389_4b815f793a.jpg
 extracting: 2751694538_fffa3d307d.jpg
 extracting: 2809793070_1a3387cd6e.jpg
 extracting: 2871962580_b85ce502ba.jpg
 extracting: 2929272606_2a5923b38e.jpg
 extracting: 3015898903_70bebb8903.jpg
 extracting: 3018847610_0bf4d7e43d.jpg
 extracting: 3172384527_b107385a20.jpg
 extracting: 3246804978_ea2c9e56f2.jpg
 extracting: 3268191118_ba25fabab6.jpg
 extracting: 3288173388_03bc2a844d.jpg
 extracting: 3451523035_b61d79f6a8.jpg
 extracting: 3502563726_30d1ce29c8.jpg
 extracting: 3534183988_3763593dfb.jpg
 extracting: 3535768334_a3924bcccd.jpg
 extracting: 3602676311_824b2c04ba.jpg
 extracting: 3627076769_3b71e73018.jpg
 extracting: 3722572342_6904d11d52.jpg
 extracting: 1077931201_1e0bb83105.jpg
 extracting: 1308472581_9961782889.jpg
 extracting: 1332722096_1e3de8ae70.jpg
 extracting: 1427391496_ea512cbe7f.jpg
 extracting: 1776981714_5b224d0f7a.jpg
 extracting: 1808007704_ee8a93abb4.jpg
 extracting: 2043427251_83b746da8e.jpg
 extracting: 2238019823_79318d1f11.jpg
 extracting: 2273871383_1ddb3562ea.jpg
 extracting: 2423292784_166ee54e0b.jpg
 extracting: 2629346153_155ba73ae9.jpg
 extracting: 2664102751_d5a737a566.jpg
 extracting: 2718495608_d8533e3ac5.jpg
 extracting: 2747714500_49476225c6.jpg
 extracting: 2834752476_3177e617f1.jpg
 extracting: 2869765795_21a398cb24.jpg
 extracting: 2872963574_52ab5182cb.jpg
 extracting: 2956413620_d59de03a06.jpg
 extracting: 3006217970_90b42e6b27.jpg
 extracting: 3048211972_db71d104c2.jpg
 extracting: 3109124656_626b596d5e.jpg
 extracting: 3203453897_6317aac6ff.jpg
 extracting: 3211581957_df2f7e2236.jpg
 extracting: 3245460937_2710a82709.jpg
 extracting: 3263741906_6e4508d1c8.jpg
 extracting: 3276448136_0d9f5069c5.jpg
 extracting: 3323528927_7b21081271.jpg
 extracting: 3341477531_4e37450f35.jpg
 extracting: 3363750526_efcedc47a9.jpg
 extracting: 3373481779_511937e09d.jpg
 extracting: 3420323191_d66e003264.jpg
 extracting: 3429194423_98e911a101.jpg
 extracting: 3459858555_c3f0087a72.jpg
 extracting: 3567604049_da9e1be4ba.jpg
 extracting: 3595412126_4020d4643b.jpg
 extracting: 3720210639_18bb34e475.jpg
 extracting: 1042590306_95dea0916c.jpg
 extracting: 1215334959_b1970965f7.jpg
 extracting: 1342766791_1e72f92455.jpg
 extracting: 1732217138_aa0199ef87.jpg
 extracting: 1884065356_c6c34b4568.jpg
 extracting: 2045109977_b00ec93491.jpg
 extracting: 2095007523_591f255708.jpg
 extracting: 2609900643_c07bcb0bae.jpg
 extracting: 2618866067_07cbc83dc5.jpg
 extracting: 2621415349_ef1a7e73be.jpg
 extracting: 2866696346_4dcccbd3a5.jpg
 extracting: 2906054175_e33af79522.jpg
 extracting: 3084711346_fda0f5a3e6.jpg
 extracting: 3092370204_029b6bc10a.jpg
 extracting: 3139238055_2817a0c7d8.jpg
 extracting: 3169276423_6918dd4da1.jpg
 extracting: 3204354161_caf89ec784.jpg
 extracting: 3211556865_d1d9becf69.jpg
 extracting: 3222055946_45f7293bb2.jpg
 extracting: 3293018193_e4e0c8db7c.jpg
 extracting: 3324746155_71e14f60ce.jpg
 extracting: 3359530430_249f51972c.jpg
 extracting: 3367758711_a8c09607ac.jpg
 extracting: 3447876218_4ccf42d7a0.jpg
 extracting: 3466891862_9afde75568.jpg
 extracting: 3497236690_a48bf7ac42.jpg
 extracting: 3595216998_0a19efebd0.jpg
 extracting: 3673970325_4e025069e9.jpg
 extracting: 3685372942_6ae935b34e.jpg
 extracting: 1305564994_00513f9a5b.jpg
 extracting: 1306145560_1e37081b91.jpg
 extracting: 1433577867_39a1510c43.jpg
 extracting: 1436760519_8d6101a0ed.jpg
 extracting: 2185793891_5a5e903ca6.jpg
 extracting: 2255685792_f70474c6db.jpg
 extracting: 2261962622_e9318a95eb.jpg
 extracting: 2332540384_4cf26406a9.jpg
 extracting: 2442243868_abe8f74fb4.jpg
 extracting: 2597308074_acacc12e1b.jpg
 extracting: 2753506871_dc38e7d153.jpg
 extracting: 3006095077_1992b677f8.jpg
 extracting: 3120189281_1938460e85.jpg
 extracting: 3167379087_927ff05a35.jpg
 extracting: 3250589803_3f440ba781.jpg
 extracting: 3285214689_f0219e9671.jpg
 extracting: 3287963317_186491ee78.jpg
 extracting: 3361210233_962d630ec5.jpg
 extracting: 3368207495_1e2dbd6d3f.jpg
 extracting: 3379839396_0cd84b55f1.jpg
 extracting: 3385956569_a849218e34.jpg
 extracting: 3396036947_0af6c3aab7.jpg
 extracting: 3397228832_8ce5b1c26f.jpg
 extracting: 3425127583_611200619a.jpg
 extracting: 3442978981_53bf1f45f3.jpg
 extracting: 3477315700_52a4d740a5.jpg
 extracting: 3482668767_66004ce736.jpg
 extracting: 3494394662_3edfd4a34c.jpg
 extracting: 3496983524_b21ecdb0c7.jpg
 extracting: 3543294190_0037c59607.jpg
 extracting: 3562282690_cd2a95fe9e.jpg
 extracting: 3621652774_fd9634bd5b.jpg
 extracting: 3705430840_e108de78bf.jpg
 extracting: 1067790824_f3cc97239b.jpg
 extracting: 1415591512_a84644750c.jpg
 extracting: 1449692616_60507875fb.jpg
 extracting: 1468103286_96a6e07029.jpg
 extracting: 2114355355_9d7e2d8178.jpg
 extracting: 2172493537_128bc8b187.jpg
 extracting: 2194494220_bb2178832c.jpg
 extracting: 2396100671_3a9d67f03d.jpg
 extracting: 2425262733_afe0718276.jpg
 extracting: 2458033289_f0616879df.jpg
 extracting: 2467856402_0490413d38.jpg
 extracting: 2533642917_a5eace85e6.jpg
 extracting: 2542662402_d781dd7f7c.jpg
 extracting: 2641770481_c98465ff35.jpg
 extracting: 2684322797_85406f571d.jpg
 extracting: 2760715910_87c7bdeb87.jpg
 extracting: 2860400846_2c1026a573.jpg
 extracting: 2867699650_e6ddb540de.jpg
 extracting: 3106026005_473a7b1c8c.jpg
 extracting: 3133825703_359a0c414d.jpg
 extracting: 3139895886_5a6d495b13.jpg
 extracting: 3211210739_3dea005fde.jpg
 extracting: 3249891130_b241591e89.jpg
 extracting: 3269380710_9161b0bd00.jpg
 extracting: 3308997740_91765ecdcc.jpg
 extracting: 3339768802_8ab768558a.jpg
 extracting: 3360930596_1e75164ce6.jpg
 extracting: 3479423813_517e93a43a.jpg
 extracting: 3516960094_87fb4889de.jpg
 extracting: 3532412342_e0a004b404.jpg
 extracting: 3587009091_37188fd07e.jpg
 extracting: 3594566537_55bd712fdb.jpg
 extracting: 3596428453_8cfdec4869.jpg
 extracting: 3619381206_5bc8b406f9.jpg
 extracting: 1434607942_da5432c28c.jpg
 extracting: 1937262236_cbf5bfa101.jpg
 extracting: 1994416869_4dd769a806.jpg
 extracting: 2281006675_fde04e93dd.jpg
 extracting: 2466420387_86fe77c966.jpg
 extracting: 2616508003_fa5ca5780d.jpg
 extracting: 2745663684_650f84e1e6.jpg
 extracting: 2792195540_af5fb95caa.jpg
 extracting: 2895700779_fac1d9d278.jpg
 extracting: 3145967309_b33abe4d84.jpg
 extracting: 3155451946_c0862c70cb.jpg
 extracting: 3183883750_b6acc40397.jpg
 extracting: 3222041930_f642f49d28.jpg
 extracting: 3266306177_7994dc2865.jpg
 extracting: 3439331800_e71e1d808f.jpg
 extracting: 3465000218_c94e54e208.jpg
 extracting: 3473534758_1ae3847781.jpg
 extracting: 3490597800_8f94f7d353.jpg
 extracting: 3497224764_6e17544e0d.jpg
 extracting: 3526897578_3cf77da99b.jpg
 extracting: 3534548254_7bee952a0e.jpg
 extracting: 3576536763_3c8c4f232e.jpg
 extracting: 3580375310_46ec3e476c.jpg
 extracting: 3599442049_e448c7c9b2.jpg
 extracting: 3681324243_b69fa90842.jpg
 extracting: 3736786640_70df13be2c.jpg
 extracting: 1479028910_3dab3448c8.jpg
 extracting: 1527333441_af65636a74.jpg
 extracting: 2075321027_c8fcbaf581.jpg
 extracting: 2084217208_7bd9bc85e5.jpg
 extracting: 2085078076_b9db242d21.jpg
 extracting: 2198494923_8159551be4.jpg
 extracting: 2252264255_03fefc25af.jpg
 extracting: 2414384480_096867d695.jpg
 extracting: 2419591925_1038c6c570.jpg
 extracting: 2444134813_20895c640c.jpg
 extracting: 2479652566_8f9fac8af5.jpg
 extracting: 2525455265_f84ba72bd7.jpg
 extracting: 2604305843_ebe3e8a328.jpg
 extracting: 2676651833_3bb42bbb32.jpg
 extracting: 2701487024_e866eb4550.jpg
 extracting: 2704379125_9c35650d16.jpg
 extracting: 2715289538_d77c8d0a85.jpg
 extracting: 2877511986_c965ced502.jpg
 extracting: 2911928620_06c3fa293e.jpg
 extracting: 3016726158_4d15b83b06.jpg
 extracting: 3030823649_3b7b6c728d.jpg
 extracting: 3053785363_50392f2c53.jpg
 extracting: 3085973779_29f44fbdaa.jpg
 extracting: 3132760860_3e743a935d.jpg
 extracting: 3135826945_f7c741e5b7.jpg
 extracting: 3222250187_ef610f267e.jpg
 extracting: 3351370405_e417e38f52.jpg
 extracting: 3399284917_721aefe2a7.jpg
 extracting: 3436074878_21515a6706.jpg
 extracting: 3710468717_c051d96a5f.jpg
 extracting: 1396064003_3fd949c9dd.jpg
 extracting: 2102030040_2e8f4738f7.jpg
 extracting: 2165461920_1a4144eb2b.jpg
 extracting: 2244613488_4d1f9edb33.jpg
 extracting: 2293424366_7b5fcd2398.jpg
 extracting: 2306674172_dc07c7f847.jpg
 extracting: 2341254813_c53a5ef27a.jpg
 extracting: 2525232298_cf42d415ab.jpg
 extracting: 2543679402_9359e1ee4e.jpg
 extracting: 2585141045_b496a7b7c4.jpg
 extracting: 2598979962_c01811cfca.jpg
 extracting: 2662537919_18a29fca8a.jpg
 extracting: 2714674623_8cd05ac114.jpg
 extracting: 2942798367_022df04b49.jpg
 extracting: 2978271431_f6a7f19825.jpg
 extracting: 3028561714_83fb921067.jpg
 extracting: 3168123064_d1983b8f92.jpg
 extracting: 3270691950_88583c3524.jpg
 extracting: 3279524184_d5e2ffbaed.jpg
 extracting: 3293945284_6a04e477a9.jpg
 extracting: 3315726723_64c9b0a945.jpg
 extracting: 3364026240_645d533fda.jpg
 extracting: 3441145615_b4fcd9eea0.jpg
 extracting: 3443326696_fe0549c5be.jpg
 extracting: 3504881781_6a842e043b.jpg
 extracting: 3527524436_a54aca78a9.jpg
 extracting: 3574627719_790325430e.jpg
 extracting: 3592992234_6d3fe58a70.jpg
 extracting: 3606909929_90a1a072b7.jpg
 extracting: 3612484827_0e479f9ee8.jpg
 extracting: 3679405397_bb130ea3c2.jpg
 extracting: 1472882567_33dc14c8b6.jpg
 extracting: 2125626631_a4b63af97e.jpg
 extracting: 2381583688_a6dd0a7279.jpg
 extracting: 2500826039_165e75b20c.jpg
 extracting: 2502856739_490db7a657.jpg
 extracting: 2574509968_e4692ae169.jpg
 extracting: 2596514158_c516e57974.jpg
 extracting: 2679926555_b11cf45595.jpg
 extracting: 2701042060_92508ea8fa.jpg
 extracting: 2831672255_d779807c14.jpg
 extracting: 2909955251_4b326a46a7.jpg
 extracting: 2995461857_dd26188dcf.jpg
 extracting: 3122497129_d08f5729b8.jpg
 extracting: 3164347907_2813f8ff0b.jpg
 extracting: 3209350613_eb86579ee8.jpg
 extracting: 3209523192_05a4cef844.jpg
 extracting: 3213622536_31da7f6682.jpg
 extracting: 3225880532_c8d5d1d798.jpg
 extracting: 3251906388_c09d44340e.jpg
 extracting: 3315353266_70f0bbb1c3.jpg
 extracting: 3365602213_dd3287a633.jpg
 extracting: 3372340429_91c4f4af30.jpg
 extracting: 3399616238_77acf4ee12.jpg
 extracting: 3429391520_930b153f94.jpg
 extracting: 3430287726_94a1825bbf.jpg
 extracting: 3457572788_e1fe4f6480.jpg
 extracting: 3532205154_5674b628ea.jpg
 extracting: 3626689571_5817f99c0e.jpg
 extracting: 3686078365_9e655e238f.jpg
 extracting: 3719461451_07de35af3a.jpg
 extracting: 1453366750_6e8cf601bf.jpg
 extracting: 1584315962_5b0b45d02d.jpg
 extracting: 2089122314_40d5739aef.jpg
 extracting: 2164363131_6930455d45.jpg
 extracting: 2252403744_148fc11f68.jpg
 extracting: 2272823323_3b7291cd47.jpg
 extracting: 2294516804_11e255807a.jpg
 extracting: 2363100645_c3423a0433.jpg
 extracting: 2522297487_57edf117f7.jpg
 extracting: 2618322793_5fb164d86a.jpg
 extracting: 2626158969_ac09aeb88d.jpg
 extracting: 2671602981_4edde92658.jpg
 extracting: 2708686056_1b8f356264.jpg
 extracting: 2710416789_555180e399.jpg
 extracting: 2726301121_95a2fbd22b.jpg
 extracting: 2911107495_e3cec16a24.jpg
 extracting: 2917843040_7c9caaaa8a.jpg
 extracting: 2982928615_06db40f4cd.jpg
 extracting: 3019923691_3b3c5a4766.jpg
 extracting: 3090957866_f1b2b7f214.jpg
 extracting: 3211316116_a2462e327d.jpg
 extracting: 3229519418_040f05ced1.jpg
 extracting: 3263141261_db3a4798b5.jpg
 extracting: 3342855466_44038a8aa3.jpg
 extracting: 3354414391_a3908bd4ff.jpg
 extracting: 3405113041_4b72c24801.jpg
 extracting: 3437147889_4cf26dd525.jpg
 extracting: 3458215674_2aa5e64643.jpg
 extracting: 3480379024_545e8ec818.jpg
 extracting: 3580741947_cc64a83648.jpg
 extracting: 3582465732_78f77f34ae.jpg
 extracting: 3613667665_1881c689ea.jpg
 extracting: 3629492654_619d7b67ee.jpg
 extracting: 3661659196_6ed90f96c0.jpg
 extracting: 3692746368_ab7d97ab31.jpg
 extracting: 1402641725_5e027ecaa7.jpg
 extracting: 1478294229_7e1c822fea.jpg
 extracting: 1569562856_eedb5a0a1f.jpg
 extracting: 1721637099_93e9ec2a2f.jpg
 extracting: 2021613437_d99731f986.jpg
 extracting: 2151300603_248a9fe715.jpg
 extracting: 2290330500_e7bdaa58e1.jpg
 extracting: 2301379282_5fbcf230d1.jpg
 extracting: 2311690895_0d6efe11c8.jpg
 extracting: 2374652725_32f90fa15c.jpg
 extracting: 2480327661_fb69829f57.jpg
 extracting: 2595102568_347f6d4b07.jpg
 extracting: 2708634088_a4686be24c.jpg
 extracting: 2800004913_c8394ba332.jpg
 extracting: 2882056260_4399dd4d7c.jpg
 extracting: 2944025729_5aecda30ee.jpg
 extracting: 2987195421_e830c59fb6.jpg
 extracting: 2998861375_02817e0147.jpg
 extracting: 3006926228_cf3c067b3e.jpg
 extracting: 3019199755_a984bc21b1.jpg
 extracting: 3041384194_04316bd416.jpg
 extracting: 3106791484_13e18c33d8.jpg
 extracting: 3109780402_dbae082dc5.jpg
 extracting: 3210359094_ee51285301.jpg
 extracting: 3221128704_d1205db79b.jpg
 extracting: 3256272547_5ae6c66293.jpg
 extracting: 3273625566_2454f1556b.jpg
 extracting: 3432550415_e7b77232de.jpg
 extracting: 3449114979_6cdc3e8da8.jpg
 extracting: 3534512991_f9fd66f165.jpg
 extracting: 3630641436_8f9ac5b9b2.jpg
 extracting: 3655074079_7df3812bc5.jpg
 extracting: 1131155939_b4b457b05e.jpg
 extracting: 1408958345_68eea9a4e4.jpg
 extracting: 1464120327_d90279ca3a.jpg
 extracting: 1573017288_4d481856e2.jpg
 extracting: 2374247382_023a86b9ca.jpg
 extracting: 2496370758_a3fbc49837.jpg
 extracting: 2591603141_33d6397e0a.jpg
 extracting: 2709359730_13bca100af.jpg
 extracting: 2721656220_5f4cda8bc1.jpg
 extracting: 2860872588_f2c7b30e1a.jpg
 extracting: 2943079526_e9033a6556.jpg
 extracting: 3006094603_c5b32d2758.jpg
 extracting: 3154693053_cfcd05c226.jpg
 extracting: 3171035252_dba286ae5c.jpg
 extracting: 3182996527_70d9c323d5.jpg
 extracting: 3185662156_c877583c53.jpg
 extracting: 3186073578_6e115f45f5.jpg
 extracting: 3241892328_4ebf8b21ce.jpg
 extracting: 3264678536_46601d25f0.jpg
 extracting: 3315616181_15dd137e27.jpg
 extracting: 3320032226_63390d74a6.jpg
 extracting: 3331525712_af1dcc47f2.jpg
 extracting: 3333039854_461329aac2.jpg
 extracting: 3348385580_10b53391f9.jpg
 extracting: 3354474353_daf9e168cf.jpg
 extracting: 3429351222_17ae744daf.jpg
 extracting: 3457364788_3514a52091.jpg
 extracting: 3552435734_04da83b905.jpg
 extracting: 3564738125_10400f69c0.jpg
 extracting: 3569406219_f37ebf7b92.jpg
 extracting: 3582914739_bef2828a06.jpg
 extracting: 1463638541_c02cfa04dc.jpg
 extracting: 1799188614_b5189728ba.jpg
 extracting: 2228167286_7089ab236a.jpg
 extracting: 2281075738_230892b241.jpg
 extracting: 2352414953_10f3cd0f1f.jpg
 extracting: 2434074318_e35a567220.jpg
 extracting: 2543017787_9720b4fa1c.jpg
 extracting: 2589156742_c46bc82137.jpg
 extracting: 2742426734_291df6da08.jpg
 extracting: 2752919987_8bfca604ab.jpg
 extracting: 2830309113_c79d7be554.jpg
 extracting: 2839932205_3c9c27cd99.jpg
 extracting: 2875583266_4da13ae12d.jpg
 extracting: 2877088081_7ca408cb25.jpg
 extracting: 2904997007_23d4b94101.jpg
 extracting: 2955673642_4279b32097.jpg
 extracting: 2991994607_06f24ec7a6.jpg
 extracting: 3056569684_c264c88d00.jpg
 extracting: 3170110692_d1e0e66cee.jpg
 extracting: 3244586044_205d5ae2ba.jpg
 extracting: 3262849619_0bc4f88ef9.jpg
 extracting: 3332467180_d72f9b067d.jpg
 extracting: 3356938707_d95ba97430.jpg
 extracting: 3368819708_0bfa0808f8.jpg
 extracting: 3372251830_baa3665928.jpg
 extracting: 3425853460_bfcd0b41f6.jpg
 extracting: 3458577912_67db47209d.jpg
 extracting: 3537474810_cf676b3259.jpg
 extracting: 3590294974_4ef98f013e.jpg
 extracting: 3601843201_4809e66909.jpg
 extracting: 3649307685_60c1294d2a.jpg
 extracting: 3703107969_175da4b276.jpg
 extracting: 1095980313_3c94799968.jpg
 extracting: 1321723162_9d4c78b8af.jpg
 extracting: 1480712062_32a61ad4b7.jpg
 extracting: 1499581619_a5f65a882c.jpg
 extracting: 2097489021_ca1b9f5c3b.jpg
 extracting: 2144846312_d4c738dc6c.jpg
 extracting: 2258662398_2797d0eca8.jpg
 extracting: 2324779494_5e72d29171.jpg
 extracting: 2331510788_986809bbb4.jpg
 extracting: 2351479551_e8820a1ff3.jpg
 extracting: 2435685480_a79d42e564.jpg
 extracting: 2510560080_1439fe32f2.jpg
 extracting: 2522230304_1581d52961.jpg
 extracting: 2660008870_b672a4c76a.jpg
 extracting: 2662816021_ac474e0fde.jpg
 extracting: 2709648336_15455e60b2.jpg
 extracting: 2921094201_2ed70a7963.jpg
 extracting: 3004291093_35d6fd8548.jpg
 extracting: 3046190891_05c6ecd9b6.jpg
 extracting: 3047264032_14393ecea8.jpg
 extracting: 3064716525_b8418d4946.jpg
 extracting: 3065560742_f6e266ccd9.jpg
 extracting: 3211577298_14296db6fd.jpg
 extracting: 3217291172_10ef70af88.jpg
 extracting: 3229898555_16877f5180.jpg
 extracting: 3268407162_6274e0f74f.jpg
 extracting: 3424424006_98f9d1921c.jpg
 extracting: 3446586125_cafa0bfd67.jpg
 extracting: 3501781809_88429e3b83.jpg
 extracting: 3532028205_9ddd7599f8.jpg
 extracting: 1169307342_e7a4685a5c.jpg
 extracting: 1287064529_aa4e4f3c31.jpg
 extracting: 1352410176_af6b139734.jpg
 extracting: 2056930414_d2b0f1395a.jpg
 extracting: 2210368267_0615754b48.jpg
 extracting: 2268596214_ca532f5c63.jpg
 extracting: 2512876666_9da03f9589.jpg
 extracting: 2682194299_92005b26c6.jpg
 extracting: 2845845721_d0bc113ff7.jpg
 extracting: 2865376471_43c5e6b941.jpg
 extracting: 3041170372_c4376cd497.jpg
 extracting: 3087485737_cb09bc80b6.jpg
 extracting: 3138399980_d6ab8b2272.jpg
 extracting: 3217910740_d1d61c08ab.jpg
 extracting: 3230132205_dccfafa5ee.jpg
 extracting: 3259222690_69737f2a6e.jpg
 extracting: 3274879561_74997bbfff.jpg
 extracting: 3371567529_606fa3452b.jpg
 extracting: 3388094307_5a83be64a5.jpg
 extracting: 3416091866_a96003d652.jpg
 extracting: 3442540072_b22ca2410f.jpg
 extracting: 3484019369_354e0b88c0.jpg
 extracting: 3613585080_36629d8157.jpg
 extracting: 3614582606_16bd88dab2.jpg
 extracting: 3616771728_2c16bf8d85.jpg
 extracting: 3618908551_7fd2de5710.jpg
 extracting: 3666188047_e81e1d97a7.jpg
 extracting: 3668518431_43abb169eb.jpg
 extracting: 3695517194_2a6b604cb2.jpg
 extracting: 3728015645_b43a60258b.jpg
 extracting: 1019604187_d087bf9a5f.jpg
 extracting: 1022454428_b6b660a67b.jpg
 extracting: 1343426964_cde3fb54e8.jpg
 extracting: 2064790732_219e52e19c.jpg
 extracting: 2101808682_0d66ef4a08.jpg
 extracting: 2157003092_eaeb977789.jpg
 extracting: 2186367337_0ce9ce2104.jpg
 extracting: 2421446839_fe7d46c177.jpg
 extracting: 2474918824_88660c7757.jpg
 extracting: 2512683710_991c9d466d.jpg
 extracting: 2600867924_cd502fc911.jpg
 extracting: 2698487246_e827404cac.jpg
 extracting: 2769605231_dae8b30201.jpg
 extracting: 2833560457_24aedf3bef.jpg
 extracting: 2876994989_a4ebbd8491.jpg
 extracting: 2882589788_cb0b407a8d.jpg
 extracting: 2884651479_12e400ee58.jpg
 extracting: 3079917032_3cfacb2fd7.jpg
 extracting: 3183195653_11b66acb34.jpg
 extracting: 3192069971_83c5a90b4c.jpg
 extracting: 3336682980_1082a66878.jpg
 extracting: 3374223949_90776ba934.jpg
 extracting: 3487419819_e3f89444ce.jpg
 extracting: 3512791890_eb065b460a.jpg
 extracting: 3648160673_0c783236a6.jpg
 extracting: 3663307538_468739e4c3.jpg
 extracting: 3697359692_8a5cdbe4fe.jpg
 extracting: 3721812313_6000566803.jpg
 extracting: 3726590391_bc6e729bb6.jpg
 extracting: 1460500597_866fa0c6f3.jpg
 extracting: 2064417101_3b9d817f4a.jpg
 extracting: 2068960566_21e85ae0dc.jpg
 extracting: 2245348304_08bc5642f1.jpg
 extracting: 2248487956_2603f55ab9.jpg
 extracting: 2290589734_b588471345.jpg
 extracting: 2318721455_80c6644441.jpg
 extracting: 2396669903_5217a83641.jpg
 extracting: 2451285022_59255e7fd9.jpg
 extracting: 2527303359_6c3dc3f282.jpg
 extracting: 2689358407_9932f1b20c.jpg
 extracting: 2734219983_fe86a60bf9.jpg
 extracting: 2764732789_1392e962d0.jpg
 extracting: 2768021570_46bc6325e3.jpg

In [ ]:
!wget  https://raw.githubusercontent.com/text-machine-lab/MUTT/refs/heads/master/data/flickr/Flickr8k.token.txt

--2025-03-26 05:20:00--  https://raw.githubusercontent.com/text-machine-lab/MUTT/refs/heads/master/data/flickr/Flickr8k.token.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3395237 (3.2M) [text/plain]
Saving to: ‘Flickr8k.token.txt’

Flickr8k.token.txt  100%[===================>]   3.24M  --.-KB/s    in 0.08s

2025-03-26 05:20:00 (41.8 MB/s) - ‘Flickr8k.token.txt’ saved [3395237/3395237]

In [ ]:
!wget -q --show-progress http://nlp.stanford.edu/data/glove.42B.300d.zip

glove.42B.300d.zip  100%[===================>]   1.75G   182KB/s    in 59m 24s

In [ ]:
!unzip -q glove.42B.300d.zip

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from tensorflow.keras.applications.inception_v3 import InceptionV3, preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array, load_img
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

from tensorflow.keras.layers import Input, Dense, LSTM, Embedding, add, Dropout,\
Activation,Flatten, BatchNormalization, RepeatVector, TimeDistributed,Reshape,concatenate

from tensorflow.keras.models import Model, load_model
import tensorflow.keras.preprocessing.image as tf_image
import tensorflow.keras.applications.inception_v3 as inception

import string
from string import punctuation
from nltk import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
import re
from tqdm import tqdm

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
encode_model = InceptionV3(weights='imagenet')
encode_model = Model(encode_model.input, encode_model.layers[-2].output)
WIDTH = 299
HEIGHT = 299
OUTPUT_DIM = 2048
START = "startseq"
STOP = "endseq"
EPOCHS = 10
preprocess_input = inception.preprocess_input

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/inception_v3/inception_v3_weights_tf_dim_ordering_tf_kernels.h5
96112376/96112376 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step

In [ ]:
import tensorflow.keras.preprocessing.image as tf_image

In [ ]:
def encodeImage(img):
  img = img.resize((WIDTH, HEIGHT))

  x = tf_image.img_to_array(img)

  x = np.expand_dims(x, axis=0)

  x = preprocess_input(x)

  x = encode_model.predict(x) # Get the encoding vector for the image
  x = np.reshape(x, OUTPUT_DIM )

  return x

In [ ]:
import pandas as pd
token = pd.read_csv('Flickr8k.token.txt', delimiter='\t', header=None, names=['img','caption'])
token.head()

,img,caption
0,1000268201_693b08cb0e.jpg#0,A child in a pink dress is climbing up a set o...
1,1000268201_693b08cb0e.jpg#1,A girl going into a wooden building .
2,1000268201_693b08cb0e.jpg#2,A little girl climbing into a wooden playhouse .
3,1000268201_693b08cb0e.jpg#3,A little girl climbing the stairs to her playh...
4,1000268201_693b08cb0e.jpg#4,A little girl in a pink dress going into a woo...

In [ ]:
token['img_id'] = token['img'].apply(lambda x: x.split('.')[0])
token.head(2)

,img,caption,img_id
0,1000268201_693b08cb0e.jpg#0,A child in a pink dress is climbing up a set o...,1000268201_693b08cb0e
1,1000268201_693b08cb0e.jpg#1,A girl going into a wooden building .,1000268201_693b08cb0e

In [ ]:
token['img'] = token['img'].apply(lambda x: x.split('#')[0])
token['img'].head(2)

0    1000268201_693b08cb0e.jpg
1    1000268201_693b08cb0e.jpg
Name: img, dtype: object

In [ ]:
encode_model = InceptionV3(weights='imagenet')
encode_model = Model(encode_model.input, encode_model.layers[-2].output)
# we r not interested in classification we want the 2nd last layer
WIDTH = 299
HEIGHT = 299
OUTPUT_DIM = 2048
START = "startseq"  # start tag
STOP = "endseq"     # end tag to differentiate the usual caption
EPOCHS = 10
preprocess_input = inception.preprocess_input

In [ ]:
token['caption'][0:2]

0    A child in a pink dress is climbing up a set o...
1                A girl going into a wooden building .
Name: caption, dtype: object

In [ ]:
token['caption'] = token['caption'].apply(lambda x: START+' '+x+' '+STOP)
token['caption'][1]

'startseq A girl going into a wooden building . endseq'

In [ ]:
token['caption'] = token['caption'].apply(lambda x: re.sub('['+punctuation+']',' ',x))
token['caption'] = token['caption'].apply(lambda x: re.sub("\d"," ", x))
token['caption'] = token['caption'].replace('-', ' ')
token['caption'] = token['caption'].apply(lambda x: re.sub("\s+"," ", x))
token['caption'] = token['caption'].str.lower()

In [ ]:
word_count_threshold = 5
word_counts ={}
for caption in token['caption']:
  for w in word_tokenize(caption):
    word_counts[w] = word_counts.get(w,0) + 1

In [ ]:
vocab = [w for w in word_counts if word_counts[w] >= word_count_threshold]
print('preprocessed word count %d ==> %d' % (len(word_counts), len(vocab)))

preprocessed word count 8442 ==> 2973

In [ ]:
caption_lens=[]
for caption in token['caption']:
  words=word_tokenize(caption)
  words=[w for w in words if w in vocab]
  caption_lens.append(len(words))
max_length=max(caption_lens)

In [ ]:
print('maximum caption length is:',max_length)

maximum caption length is: 37

In [ ]:
idxtoword = {}
wordtoidx = {}

ix = 1
for w in vocab:
    wordtoidx[w] = ix
    idxtoword[ix] = w
    ix += 1

vocab_size = len(idxtoword) + 1
vocab_size

2974

In [ ]:
embeddings_index = {}
f = open( 'glove.42B.300d.txt', encoding="utf-8")

for line in f:
    line=line.strip()
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs

f.close()
print(f'Found {len(embeddings_index)} word vectors.')

Found 1917494 word vectors.

In [ ]:
embedding_dim = 300

embedding_matrix = np.zeros((vocab_size, embedding_dim))

for word, i in wordtoidx.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

In [ ]:
embedding_matrix.shape

(2974, 300)

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt

In [ ]:
def data_generator(data, encoded_images, wordtoidx, max_length, num_photos_per_batch):
  # x1 - Training data for photos
  # x2 - The caption that goes with each photo
  # y - The predicted rest of the caption
  x1, x2, y = [], [], []
  n=0
  while True:
    for k,caption in enumerate(data['caption']):
      n+=1
      photo = encoded_images[data['id'][k]]

      seq = [wordtoidx[word] for word in word_tokenize(caption) if word in wordtoidx]
        # Generate a training case for every possible sequence and outcome
      for i in range(1, len(seq)):
        in_seq, out_seq = seq[:i], seq[i]
        in_seq = pad_sequences([in_seq], maxlen=max_length)[0]
        out_seq = to_categorical([out_seq], num_classes=vocab_size)[0]
        x1.append(photo)
        x2.append(in_seq)
        y.append(out_seq)
      if n==num_photos_per_batch:
        yield ([np.array(x1), np.array(x2)], np.array(y))
        # next when generator gets called iteration will start from where we left off
        # this makes it make a pass through the complete data in an epoch
        x1, x2, y = [], [], []
        n=0

In [ ]:
from tensorflow.keras.layers import LSTM, Embedding, TimeDistributed, Dense, RepeatVector,\
                         Activation, Flatten, Reshape, concatenate, Dropout, BatchNormalization,add

In [ ]:
inputs1 = Input(shape=(OUTPUT_DIM,))
fe1 = Dropout(0.5)(inputs1)
fe2 = Dense(256, activation='relu')(fe1)
inputs2 = Input(shape=(max_length,))
se1 = Embedding(vocab_size, embedding_dim, mask_zero=True)(inputs2)
se2 = Dropout(0.5)(se1)
se3 = LSTM(256)(se2)
decoder1 = add([fe2, se3])
decoder2 = Dense(256, activation='relu')(decoder1)
outputs = Dense(vocab_size, activation='softmax')(decoder2)
caption_model = Model(inputs=[inputs1, inputs2], outputs=outputs)

In [ ]:
caption_model.layers[2].set_weights([embedding_matrix])
caption_model.layers[2].trainable = False
caption_model.compile(loss='categorical_crossentropy', optimizer='adam')

In [ ]:
from tqdm import tqdm

In [ ]:
caption_model.optimizer.lr = 1e-4
number_pics_per_batch = 6
steps = len(data['caption'])//number_pics_per_batch

for i in tqdm(range(EPOCHS)):
    generator = data_generator(data, encoded_images, wordtoidx, max_length, number_pics_per_batch)
    caption_model.fit_generator(generator, epochs=1, steps_per_epoch=steps, verbose=1)

In [ ]:
def generateCaption(photo):
    in_text = START
    for i in range(max_length):
        sequence = [wordtoidx[w] for w in in_text.split() if w in wordtoidx]
        sequence = pad_sequences([sequence], maxlen=max_length)
        yhat = caption_model.predict([photo,sequence], verbose=0)
        yhat = np.argmax(yhat)
        word = idxtoword[yhat]
        in_text += ' ' + word
        if word == STOP:
            break
    final = in_text.split()
    final = final[1:-1]
    final = ' '.join(final)
    return final

In [ ]:



image=encoded_images[int(image_file.split('.')[0])]

image = image.reshape((1,OUTPUT_DIM))
x=plt.imread('Flicker8k.token.text'+image_file)
plt.imshow(x)
plt.show()
print("Caption:",generateCaption(image))